spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:test
  jpa:
    properties:
      hibernate:
        highlight_sql: true # hibernate - sql ? ?????
        format_sql: true  # (3) SQL pretty print
    hibernate:
      ddl-auto: create  # (1) ??? ?? ??
    show-sql: true      # (2) SQL ?? ??
  sql:
    init:
      data-locations: classpath*:db/h2/data.sql
  output:
    ansi:
      enabled: always # debug, trace? ??? ?? ??
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: TRACE # hibernate ?? ? ??
      springframework:
        orm:
