spring:
  datasource:
    url: jdbc:mysql://pre032project.ctmvpylzede6.ap-northeast-2.rds.amazonaws.com:13306/pre032project
    username: davidhan
    password: pre032project
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    org:
      springframework:
        orm:
          jpa: DEBUG
server:
  servlet:
    encoding:
      force-response: true
mail:
  address:
    admin: admin@gmail.com
jwt:
  key: zxcasdlqwealksjdioqywejkashdjkhj1k23hjkhsd87382h
  access-token-expiration-minutes: 1440
  refresh-token-expiration-minutes: 1440

